# Generated by Django 4.0.6 on 2022-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('done', 'Done'), ('help', 'Help')], default='Pending', max_length=20),
        ),
    ]
